from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_HBAO():
    g = RenderGraph('HBAO')
    g.create_pass('GBufferRaster', 'GBufferRaster', {'outputSize': 'Default', 'samplePattern': 'Center', 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back'})
    g.create_pass('ForwardLighting', 'ForwardLighting', {'envMapIntensity': 1.0, 'ambientIntensity': 0.5, 'lightIntensity': 0.5, 'envMapMirror': False})
    g.create_pass('LinearizeDepth', 'LinearizeDepth', {'depthFormat': 'R32Float'})
    g.create_pass('EnvMapPass', 'EnvMapPass', {})
    g.create_pass('RayShadow', 'RayShadow', {})
    g.create_pass('DepthPeeling', 'DepthPeeling', {'cullMode': 'Back', 'depthFormat': 'D32Float', 'minSeparationDistance': 0.5})
    g.create_pass('MaterialDoubleSided', 'MaterialDoubleSided', {})
    g.create_pass('GuardBand', 'GuardBand', {'guardBand': 64})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DeinterleaveDepth', 'DeinterleaveTexture', {})
    g.create_pass('CrossBilateralBlurBL', 'CrossBilateralBlur', {})
    g.create_pass('InterleaveTexture0', 'InterleaveTexture', {})
    g.create_pass('Ambient', 'ImageEquation', {'formula': 'I0[xy].rrra', 'format': 'RGBA32Float'})
    g.create_pass('Diffuse', 'ImageEquation', {'formula': 'I0[xy].r * I1[xy]', 'format': 'RGBA32Float'})
    g.create_pass('HBAO', 'HBAO', {'radius': 1.0, 'depthMode': 'SingleDepth', 'depthBias': 0.10000000149011612, 'exponent': 2.0})
    g.create_pass('DeinterleaveTexture', 'DeinterleaveTexture', {})
    g.add_edge('GBufferRaster.depth', 'ForwardLighting.depth')
    g.add_edge('EnvMapPass.color', 'ForwardLighting.color')
    g.add_edge('RayShadow.visibility', 'ForwardLighting.visibilityBuffer')
    g.add_edge('GBufferRaster.posW', 'RayShadow.posW')
    g.add_edge('GBufferRaster.depth', 'EnvMapPass.depth')
    g.add_edge('GBufferRaster.depth', 'LinearizeDepth.depth')
    g.add_edge('GBufferRaster.mtlData', 'MaterialDoubleSided.mtlData')
    g.add_edge('GuardBand', 'GBufferRaster')
    g.add_edge('ForwardLighting.color', 'ToneMapper.src')
    g.add_edge('LinearizeDepth.linearDepth', 'CrossBilateralBlurBL.linear depth')
    g.add_edge('ToneMapper.dst', 'Diffuse.I1')
    g.add_edge('LinearizeDepth.linearDepth', 'DeinterleaveDepth.texIn')
    g.add_edge('DeinterleaveDepth.texOut', 'HBAO.depth')
    g.add_edge('GBufferRaster.faceNormalW', 'HBAO.normals')
    g.add_edge('DeinterleaveTexture.texOut', 'HBAO.depth2')
    g.add_edge('InterleaveTexture0.texOut', 'CrossBilateralBlurBL.color')
    g.add_edge('LinearizeDepth.linearDepth', 'DepthPeeling.linearZ')
    g.add_edge('DepthPeeling.depth2', 'DeinterleaveTexture.texIn')
    g.add_edge('HBAO.ambientMap', 'InterleaveTexture0.texIn')
    g.add_edge('CrossBilateralBlurBL.colorOut', 'Ambient.I0')
    g.add_edge('Ambient.out', 'Diffuse.I0')
    g.add_edge('GBufferRaster.normW', 'RayShadow.normalW')
    g.mark_output('Ambient.out')
    g.mark_output('Diffuse.out')
    return g

HBAO = render_graph_HBAO()
try: m.addGraph(HBAO)
except NameError: None
