from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_SVAO():
    g = RenderGraph('SVAO')
    g.create_pass('GBufferRaster', 'GBufferRaster', {'outputSize': 'Default', 'samplePattern': 'Center', 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': 'Back'})
    g.create_pass('ForwardLighting', 'ForwardLighting', {'envMapIntensity': 1.0, 'ambientIntensity': 0.5, 'lightIntensity': 0.5, 'envMapMirror': False})
    g.create_pass('LinearizeDepth', 'LinearizeDepth', {'depthFormat': 'R32Float'})
    g.create_pass('EnvMapPass', 'EnvMapPass', {})
    g.create_pass('RayShadow', 'RayShadow', {})
    g.create_pass('SVAO', 'SVAO', {'radius': 0.20000000298023224, 'primaryDepthMode': 'DualDepth', 'secondaryDepthMode': 'SingleDepth', 'exponent': 2.0, 'rayPipeline': True, 'thickness': 0.0, 'stochMapDivisor': 1, 'dualAO': False, 'alphaTest': True})
    g.create_pass('DepthPeeling', 'DepthPeeling', {'cullMode': 'Back', 'depthFormat': 'D32Float', 'minSeparationDistance': 0.5})
    g.create_pass('LinearizeDepth2Ref', 'LinearizeDepth', {'depthFormat': 'R32Float'})
    g.create_pass('GuardBand', 'GuardBand', {'guardBand': 64})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Aces', 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('SVAO_ref', 'SVAO', {'radius': 0.20000000298023224, 'primaryDepthMode': 'SingleDepth', 'secondaryDepthMode': 'Raytraced', 'exponent': 2.0, 'rayPipeline': True, 'thickness': 0.0, 'stochMapDivisor': 1, 'dualAO': False, 'alphaTest': True})
    g.create_pass('DeinterleaveDepth', 'DeinterleaveTexture', {})
    g.create_pass('AOGuidedBlur', 'AOGuidedBlur', {'kernelRadius': 2, 'clampResults': True, 'enabled': False})
    g.create_pass('CrossBilateralBlurBL', 'CrossBilateralBlur', {})
    g.create_pass('InterleaveTexture0', 'InterleaveTexture', {})
    g.create_pass('Ambient', 'ImageEquation', {'formula': 'I0[xy].rrra', 'format': 'RGBA32Float'})
    g.create_pass('Diffuse', 'ImageEquation', {'formula': 'I0[xy].r * I1[xy]', 'format': 'RGBA32Float'})
    g.create_pass('DeinterleaveBrightDark', 'DeinterleaveTexture', {})
    g.create_pass('CrossBilateralBlur0', 'CrossBilateralBlur', {})
    g.create_pass('DiffuseRef', 'ImageEquation', {'formula': 'I0[xy].r * I1[xy]', 'format': 'RGBA32Float'})
    g.create_pass('AmbientRef', 'ImageEquation', {'formula': 'I0[xy].rrra', 'format': 'RGBA32Float'})
    g.create_pass('DeinterleaveTextureRef', 'DeinterleaveTexture', {})
    g.create_pass('TemporalDepthPeel', 'TemporalDepthPeel', {'minSeparationDistance': 0.5})
    g.create_pass('Depth2', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': -7.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('Depth2Ref', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': -7.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('Depth1', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': -7.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('DepthPass', 'DepthPass', {'depthFormat': 'D32Float', 'useAlphaTest': True, 'cullMode': 'Back'})
    g.create_pass('ZMipmaps', 'ZMipmaps', {'mipLevels': -1, 'threshold': 0.8999999761581421})
    g.create_pass('CompressNormals', 'CompressNormals', {'viewSpace': True, 'use16Bit': True})
    g.create_pass('DepthSelect', 'Switch', {'count': 2, 'selected': 0, 'i0': 'Temporal', 'i1': 'Peel'})
    g.add_edge('CrossBilateralBlurBL.colorOut', 'Ambient.I0')
    g.add_edge('GBufferRaster.depth', 'ForwardLighting.depth')
    g.add_edge('EnvMapPass.color', 'ForwardLighting.color')
    g.add_edge('RayShadow.visibility', 'ForwardLighting.visibilityBuffer')
    g.add_edge('GBufferRaster.posW', 'RayShadow.posW')
    g.add_edge('GBufferRaster.faceNormalW', 'RayShadow.normalW')
    g.add_edge('GBufferRaster.depth', 'EnvMapPass.depth')
    g.add_edge('GBufferRaster.depth', 'LinearizeDepth.depth')
    g.add_edge('DepthPeeling.depth2', 'LinearizeDepth2Ref.depth')
    g.add_edge('ZMipmaps.linearZMip', 'SVAO.depth')
    g.add_edge('ZMipmaps.linearZMip', 'SVAO_ref.depth')
    g.add_edge('GBufferRaster.depth', 'SVAO_ref.gbufferDepth')
    g.add_edge('GBufferRaster.depth', 'SVAO.gbufferDepth')
    g.add_edge('ToneMapper.dst', 'SVAO.color')
    g.add_edge('ToneMapper.dst', 'SVAO_ref.color')
    g.add_edge('LinearizeDepth.linearDepth', 'DepthPeeling.linearZ')
    g.add_edge('GuardBand', 'GBufferRaster')
    g.add_edge('ForwardLighting.color', 'ToneMapper.src')
    g.add_edge('AOGuidedBlur.color', 'InterleaveTexture0.texIn')
    g.add_edge('InterleaveTexture0.texOut', 'CrossBilateralBlurBL.color')
    g.add_edge('LinearizeDepth.linearDepth', 'CrossBilateralBlurBL.linear depth')
    g.add_edge('CrossBilateralBlurBL.colorOut', 'Diffuse.I0')
    g.add_edge('ToneMapper.dst', 'Diffuse.I1')
    g.add_edge('SVAO_ref.ao', 'CrossBilateralBlur0.color')
    g.add_edge('LinearizeDepth.linearDepth', 'CrossBilateralBlur0.linear depth')
    g.add_edge('CrossBilateralBlur0.colorOut', 'DiffuseRef.I0')
    g.add_edge('ToneMapper.dst', 'DiffuseRef.I1')
    g.add_edge('CrossBilateralBlur0.colorOut', 'AmbientRef.I0')
    g.add_edge('LinearizeDepth.linearDepth', 'DeinterleaveDepth.texIn')
    g.add_edge('DeinterleaveDepth.texOut', 'AOGuidedBlur.lineardepth')
    g.add_edge('SVAO.ao', 'DeinterleaveBrightDark.texIn')
    g.add_edge('DeinterleaveBrightDark.texOut', 'AOGuidedBlur.ao2')
    g.add_edge('SVAO_ref.ao', 'DeinterleaveTextureRef.texIn')
    g.add_edge('GBufferRaster.mvec', 'TemporalDepthPeel.mvec')
    g.add_edge('LinearizeDepth.linearDepth', 'TemporalDepthPeel.linearZ')
    g.add_edge('TemporalDepthPeel.depth2', 'Depth2.src')
    g.add_edge('LinearizeDepth.linearDepth', 'Depth1.src')
    g.add_edge('LinearizeDepth2Ref.linearDepth', 'Depth2Ref.src')
    g.add_edge('DepthPass', 'GBufferRaster')
    g.add_edge('LinearizeDepth.linearDepth', 'ZMipmaps.linearZ')
    g.add_edge('GBufferRaster.faceNormalW', 'CompressNormals.normalW')
    g.add_edge('CompressNormals.normalOut', 'SVAO_ref.normals')
    g.add_edge('CompressNormals.normalOut', 'SVAO.normals')
    g.add_edge('LinearizeDepth2Ref.linearDepth', 'DepthSelect.i1')
    g.add_edge('TemporalDepthPeel.depth2', 'DepthSelect.i0')
    g.add_edge('DepthSelect.out', 'SVAO.depth2')
    g.add_edge('DepthSelect.out', 'SVAO_ref.depth2')
    g.mark_output('Ambient.out')
    g.mark_output('AmbientRef.out')
    g.mark_output('Diffuse.out')
    g.mark_output('DiffuseRef.out')
    g.mark_output('Depth1.dst')
    g.mark_output('Depth2.dst')
    g.mark_output('Depth2Ref.dst')
    return g

SVAO = render_graph_SVAO()
try: m.addGraph(SVAO)
except NameError: None
